### ISSUE TITLE
[FEATURE] Crate Zone

### ISSUE THREAD

**Issue by mgrunwaldt** [lambdaclass/curse_of_myrra#854] opened 2023-09-01 21:11 UTC
## 🚀 Feature

When a player is near a crate, then a visual feedback zone should appear that means that the crate is unlocking. The zone should show somehow that there is progression in this unlock. 

To define: What happens if two players are in the zone?

**Comment by marco-paulucci** [comment] 2023-09-02 09:08
Duplicate of #785

**Closed** 2023-10-10 16:39 UTC
